# Generated by Django 5.2.7 on 2026-04-06 11:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('schedule_start_date', models.DateField(blank=True, null=True)),
                ('schedule_end_date', models.DateField(blank=True, null=True)),
                ('schedule_time_start', models.TimeField(blank=True, null=True)),
                ('schedule_time_end', models.TimeField(blank=True, null=True)),
                ('recurrence_type', models.CharField(choices=[('none', 'None'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='none', max_length=10)),
                ('recurrence_days', models.JSONField(blank=True, default=list, help_text='List of day numbers: 0=Sunday, 1=Monday, ..., 6=Saturday')),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('high', 'High'), ('emergency', 'Emergency')], default='normal', max_length=10)),
                ('duration', models.PositiveIntegerField(default=12, help_text='Duration to show this item in seconds (for non-video content)')),
                ('client_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', max_length=10)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='announcements/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('schedule_start_date', models.DateField(blank=True, null=True)),
                ('schedule_end_date', models.DateField(blank=True, null=True)),
                ('schedule_time_start', models.TimeField(blank=True, null=True)),
                ('schedule_time_end', models.TimeField(blank=True, null=True)),
                ('recurrence_type', models.CharField(choices=[('none', 'None'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='none', max_length=10)),
                ('recurrence_days', models.JSONField(blank=True, default=list, help_text='List of day numbers: 0=Sunday, 1=Monday, ..., 6=Saturday')),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('high', 'High'), ('emergency', 'Emergency')], default='normal', max_length=10)),
                ('duration', models.PositiveIntegerField(default=12, help_text='Duration to show this item in seconds (for non-video content)')),
                ('client_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', max_length=10)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('schedule_start_date', models.DateField(blank=True, null=True)),
                ('schedule_end_date', models.DateField(blank=True, null=True)),
                ('schedule_time_start', models.TimeField(blank=True, null=True)),
                ('schedule_time_end', models.TimeField(blank=True, null=True)),
                ('recurrence_type', models.CharField(choices=[('none', 'None'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='none', max_length=10)),
                ('recurrence_days', models.JSONField(blank=True, default=list, help_text='List of day numbers: 0=Sunday, 1=Monday, ..., 6=Saturday')),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('high', 'High'), ('emergency', 'Emergency')], default='normal', max_length=10)),
                ('duration', models.PositiveIntegerField(default=12, help_text='Duration to show this item in seconds (for non-video content)')),
                ('client_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', max_length=10)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(upload_to='media_files/')),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=10)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_fallback', models.BooleanField(default=False, help_text='Fallback content displays when no other content is scheduled.')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
