# Generated by Django 6.0.3 on 2026-04-05 06:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="media",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
