# Generated by Django 6.0.3 on 2026-04-05 19:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_media_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="duration",
            field=models.PositiveIntegerField(
                default=12,
                help_text="Duration to show this item in seconds (for non-video content)",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="duration",
            field=models.PositiveIntegerField(
                default=12,
                help_text="Duration to show this item in seconds (for non-video content)",
            ),
        ),
        migrations.AddField(
            model_name="media",
            name="duration",
            field=models.PositiveIntegerField(
                default=12,
                help_text="Duration to show this item in seconds (for non-video content)",
            ),
        ),
    ]
